---
- name: watchtower
  docker_compose:
    project_name: watchtower
    definition:
      version: '3'
      services:
        watchtower:
          image: containrrr/watchtower
          container_name: watchtower
          environment:
          - WATCHTOWER_NOTIFICATIONS=email
          - WATCHTOWER_NOTIFICATION_EMAIL_FROM=root@{{ ansible_host }}
          #- WATCHTOWER_NOTIFICATION_EMAIL_TO=recipient@domain.com
          #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.domain.com
          #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
          #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=user@domain.com
          #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=secretpassword
          volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          restart: always
          command: --schedule "0 0 2 * * *"