---
- name: Add key [ansible] user root
  authorized_key:
    user: root
    state: present
    key: "<insert ssh public key here>"

- name: remove user 991
  user:
    name: synapse
    state: absent
    remove: yes

- name: Add user "docker"
  user:
    name: docker
    groups: docker
    shell: /sbin/nologin
    append: yes
    comment: "dockler nologin User"
    uid: 991

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
    gid: 991