---
all:
  hosts:
    matrix.sternenlabor.de:
  children:
    caddy:
      hosts:
        matrix.sternenlabor.de:
    watchtower:
      hosts:
        matrix.sternenlabor.de:
    matrix:
      hosts:
        matrix.sternenlabor.de: